# Reference: https://docs.gradle.org/current/userguide/platforms.html

[versions]

[plugins]

[libraries]

### Testing libraries
#
#

# JUnit
junit-bom = { module = "org.junit:junit-bom", version = "5.10.0" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }

# Kotest
kotest-bom = { module = "io.kotest:kotest-bom", version = "5.6.2" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core" }
kotest-assertions-json = { module = "io.kotest:kotest-assertions-json" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest" }
kotest-property = { module = "io.kotest:kotest-property" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5" }
kotest-extensions-spring = { module = "io.kotest.extensions:kotest-extensions-spring", version = "1.1.3" }

#
### General libraries
#
#

guava = { module = "com.google.guava:guava", version = "32.1.1-jre" }
semver = { module = "io.github.z4kn4fein:semver", version = "1.4.2" }
